# Generated by Django 3.1.3 on 2022-08-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweetphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
