# Generated by Django 3.1.3 on 2022-08-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20220810_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='comments',
            new_name='comments_count',
        ),
    ]
